name: CI Demo 
on: 
    push: 
     branches: 
      - main 
    pull_request:
     branches: 
      - main 
  

jobs: 
     demo-job:
         runs-on: ubuntu-latest 

         steps: 
          - name: Checkout repository 
            uses: actions/checkout@v3 

          - name: Run demo command
            run: echo "Verifying CI is running even for pull_request events successfuly!" 
